services:
  # postgres:
  postgis:
    # image: postgres:latest
    image: postgis/postgis:15-3.3
    # container_name: postgres
    container_name: postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - postgis_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  # postgres_data:
  postgis_data:
  pgadmin_data: